// =========== SIGNUP ============

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

// =============== LOGIN =================

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// ============ FETCH TURNIP LIST ===========

export const FETCH_TURNIPS_START = 'FETCH_TURNIPS_START';
export const FETCH_TURNIPS_SUCCESS = 'FETCH_TURNIPS_SUCCESS';
export const FETCH_TURNIPS_FAILURE = 'FETCH_TURNIPS_FAILURE';

// ============ FETCH TURNIP BY ID ===========

export const FETCH_TURNIP_BY_ID_START = 'FETCH_TURNIP_BY_ID_START';
export const FETCH_TURNIP_BY_ID_SUCCESS = 'FETCH_TURNIP_BY_ID_SUCCESS';
export const FETCH_TURNIP_BY_ID_FAILURE = 'FETCH_TURNIP_BY_ID_FAILURE';

// ============ POST TURNIP ===========

export const POST_TURNIP_START = 'POST_TURNIP_START';
export const POST_TURNIP_SUCCESS = 'POST_TURNIP_SUCCESS';
export const POST_TURNIP_FAILURE = 'POST_TURNIP_FAILURE';

// ============ DELETE TURNIP ===========

export const DELETE_TURNIP_START = 'DELETE_TURNIP_START';
export const DELETE_TURNIP_SUCCESS = 'DELETE_TURNIP_SUCCESS';
export const DELETE_TURNIP_FAILURE = 'DELETE_TURNIP_FAILURE';